### PR TITLE
Fixed formatting issues

### PR DESCRIPTION
**Pull request by cryptonomicon314**
- Updated LaTeX formula to use the `\lim` command instead of just `lim` (looks better and is more  semantically correct)
- Fixed formatting of :param name: examples by adding Markdown newlines (not paragraphs!) where needed

This has only an effect on the documentation, so you don't need to submit a new PyPi package.

### CODE REVIEW

**Comment by ckald** [comment]
Btw, what is a "Markdown newline"? Is it a line ending with 2 spaces? I think that's a bad idea, my editor will even automatically trim them. Any other options?

**Comment by cryptonomicon314** [comment]
Yes, that's a markdown newline. I think the other option is to use a literal <br>.

**Comment by ckald** [comment]
I tried to force a new line after the parsed pydoc constructs, please take a look 5da6f431eecefd5db38e6f4f2e161ef9cab8d178

**Comment by cryptonomicon314** [comment]
- Config file is now YAML (breaks compatibility)
- Added support for custom CSS themes and HTML templates
- Dropped advanced support for Clojure (too much trouble to mantain)

**Comment by cryptonomicon314** [comment]
Build is failing because I still have to add the optional dependency on pandoc

**Comment by OleVik** [comment]
Any update on a merge for this? Pyccoon is a very handy utility, and the changes above would make it even better.

**Comment by ckald** [comment]
This hangs since @cryptonomicon314 mentioned that the dependency on pandoc should be made optional to pass tests. It is very undesirable to make Haskell library a dependency.

**Comment by ckald** [comment]
I will try to look at this, but not sure when I will be able to

**Comment by ckald** [comment]
I merged this and old features seem to work, but the tests are failing. Anyone who can figure this out and add some simple Haskell tests is welcome

**Pull request merged**
