### PR TITLE
Adding simple support for coffeescript

### PR DESCRIPTION
**Pull request by MichalMazurek**
Hi, 

I've added a simple coffeescript support, it suits my needs for now. The second keyword for () ->  and () => is far from perfect, but seems to work.

Thanks!

### CODE REVIEW

**Comment by ckald** [comment]
Excellent, thank you. I will include this in the next release (I've got a couple of features and optimizations to roll out). How about writing a simple test or providing a characteristic source file?

**Comment by MichalMazurek** [comment]
@ckald Alright, I'll add it tomorrow or day after :)

**Comment by ckald** [comment]
Hi, are you still there? :) It would be nice to have simplest test as there is a major rewrite ahead and I don't really speak CoffeScript.

Otherwise, I'll just merge this in

**Comment by MichalMazurek** [comment]
Hi Andrii,

I’m here didn’t had much time lately, sorry… I’ll try to do it this week.

Regards
-- 
Michał Mazurek
http://michalmazurek.eu

On 16 June 2015 at 01:38:54, Andrii Magalich (notifications@github.com) wrote:

Hi, are you still there? :) It would be nice to have simplest test as there is a major rewrite ahead and I don't really speak CoffeScript.

Otherwise, I'll just merge this in

**Comment by ckald** [comment]
Thanks for contribution

**Pull request merged**
