### PR TITLE
Added configurable options

### PR DESCRIPTION
**Pull request by cryptonomicon314**
In particular:
- The user can now customize the line breaking behaviour through the "linebreaking-behavior"
  item in the configure file (it can be set to "normal" or "pre-wrap").
  Default is "pre-wrap" for backward compatibility.
  If the user has chosen a custom CSS file (see below), this option has no effect
- The user can now supply the path to a custom css file through the "custom-css"
  item in the config file.  If no path is supplied, the default CSS file is used.
  The path is relative to the directory of the config file (not the current directory!)
- The user can now supply the path to a custom html template through the
  "custom-html-template" item in the config file.  If no path is supplied,
  the default HTML template is used. Again, the path is relative to the
  directory of the config file.

All these changes mantain backward compatibility.

### CODE REVIEW

**Comment by cryptonomicon314** [comment]
You've probably noticed that pyccoon can't rebuild its own documentation anymore, because you already changed the code to accept this kind of header:

``` markdown
# Header
```

but the comments are written with this kind of header:

``` markdown
== Header ==
```

**Comment by ckald** [comment]
Actually, I forgot to push that commit :) Already in master. This is where I stumbled upon a conflict between python comments and Markdown syntax: the code right now can't tell if the comment was parsed from inline or multiline syntax, so some lines get stripped of `#` twice and gain 1 level (h2 -> h1).

I'm figuring a way to fix this. In the meantime, one can use the second syntax as you mentioned, but those headers won't make it to the contents section of the page

**Comment by ckald** [comment]
I think the custom css file should be passed through pystache too. Then it is still configurable and we almost have a nice theming mechanism. For example, one might want to use the original Docco's vertical theme: http://jashkenas.github.io/docco/ . They should be painlessly switchable with all variables working.

A couple of themes and configurable options (I think, including "raw_custom_css" to be appended to the file) are in general better than custom stylesheets and template files. User will have hard times updating between versions of pyccoon if we suddenly decide to redesign everything. But we still can give them this option as a way to actually get new themes

The PR looks good, I'll look at it again in the morning. Thanks for contributing!

**Comment by cryptonomicon314** [comment]
> I think the custom css file should be passed through pystache too. Then it is still configurable and we almost have a nice theming mechanism.

If you can design the whole CSS file yourself, I see no need to make it a pystache template, except for reusing the same CSS file in several projects... But you are already going far enough to design your CSS file, I don't think why adding configuration options to a file you can design yourself from scratch would be that useful.

**Comment by cryptonomicon314** [comment]
Comit e0566fd fixed the markdown header problems

**Comment by ckald** [comment]
There are failing tests, I'll fix them and we actually can release a new version on PyPI

**Comment by cryptonomicon314** [comment]
I have also added better support for mathjax by including an external markdown extension (slightly customized), and added the capability to escape dollar signs ($). Do you want me to add those changes to the pull request so you can review them before releasing the new version?

**Comment by ckald** [comment]
Would be excellent.

I fixed the tests. Github did worked how I expected, so apparently we have this branch now :) https://github.com/ckald/pyccoon/tree/pr/5 . I think you can merge it into your fork and PR. Then I will remove the branch, so we won't multiply PRs

**Comment by ckald** [comment]
Can you also add a simple test for the linebreak feature? Just 2 blocks of code: with and without the "\" and verification that both are parsed as expected in both modes

**Comment by cryptonomicon314** [comment]
> Can you also add a simple test for the linebreak feature?

Yes, but not right now. I haven't looked very closely to the nitty-gritty details of parsing the source; I've been treating that as a blackbox. Can I merge your branch and upload my MathJax improvements first?

It might take a while, because my git-fu is kind of lame

**Comment by ckald** [comment]
Of course, take your time

``` sh
git fetch
git pull origin pr/5
... merging occurs ...
git push
```

If merging fails because of conflicts, inspect all conflicting files and find blocks like:

```
<<<<<< HEAD
this is a line in your branch
======
this is a line in other branch which could not be merged automatically
>>>>>> some commit
```

Fix them (i.e., edit until they are absent), then `git add` all those files, commit and you're done with merging

**Comment by ckald** [comment]
Now I remember why I was using `\`s. Here's an example of what happens with commented blocks of code:

``` python
#!/usr/bin/env python 
#-- coding: utf-8 --
```

=>

``` python
!/usr/bin/env python -- coding: utf-8 --
```

**Comment by cryptonomicon314** [comment]
We should treat comments starting with `#!` and `#-- coding:` as special, because they _are_ special, instead of having to add unwieldy markup to all normal comments.

**Comment by ckald** [comment]
I already have an issue for that #7 
But the same thing will happen with any code. Actually, this is a recurring question: how to distinguish between documentation and the commented out blocks of code?

Possible solutions:
1. Ignore. We can always say that the user should maintain the docs himself
2. Use Pygments language detector for comments? If detected language == overall file language, then it is not docs, but the code. Might be slow.
3. Use specific syntax for documentation comments? Like C/PHP do: `/**` and `**/`. E.g., in Python that could be `##`. I would hate to remember that
4. Parse only multiline comments as docs? Most editors I know comment out the blocks of code using the inline comments. This seems to be too verbose

**Comment by ckald** [comment]
#9 — moved to a new issue

**Comment by cryptonomicon314** [comment]
Done. Pushed the MathJax improvements.

**Comment by ckald** [comment]
Now PR fails for Python 3.x. 

I don't think we should have `libs` folder at all. You said that you have modified the extension - how much? Most probably you should host your version on Github and add your fork to `requirements.txt`

**Comment by cryptonomicon314** [comment]
I removed the configuration. The extension failed when the configuration was on, and I never undestood why. I can add it to the `markdown_extensions.py` file, though. Just give me half an hour or something.

**Comment by ckald** [comment]
By the way, excellent work finding this extension. I tried to implement it myself, but failed miserably. I was thinking to add a GFM-style codeblock:

``````
    ```tex
    a + b = c
    ```
``````

That might be useful for most cases. `\begin{equation}...\end{equation}` adds so much noise to the sourcefile

**Comment by cryptonomicon314** [comment]
Added a working MathExtension that doesn't break the build.

**Comment by cryptonomicon314** [comment]
> Can you also add a simple test for the linebreak feature? Just 2 blocks of code: with and without the "\" and verification that both are parsed as expected in both modes

I feel this is unnecessary, because theyare parsed the same way in both modes into HTML. Only the CSS changes.

**Comment by cryptonomicon314** [comment]
Fixed handling of special inline comments, such as shebangs and `-*- coding: utf-8 -*-`.
Didn't add support for special multiline comments yet.

**Comment by cryptonomicon314** [comment]
Done.

**Comment by cryptonomicon314** [comment]
> Let's hope our heavy usage of regular expressions will not become unbearably slow

We are adding exactly as many regular expressions as we need to handle the input in a sane way. If it becomes slow, it's the price of correctness, and something we will have to accept...

**Comment by ckald** [comment]
Oookay, releasing on PyPi is still confusing and some unexpected UTF problems popped out, but we do have a new release. The new version is `0.1.7`. Thank you very much for contributing.

**Pull request merged**
